# Combining Course Information From Every Department
* In this example I will only do the first 4 departments

## Importing Packages

In [3]:
import pandas as pd

## Combining CSV Files

In [4]:
df1 = pd.read_csv('accounting.csv')
df2 = pd.read_csv('academic_literacy_and_linguistics.csv')
df3 = pd.read_csv('allied_health.csv')
df4 = pd.read_csv('business_management.csv')

In [5]:
all_dfs = [df1, df2, df3, df4]

all_courses = pd.concat(all_dfs, ignore_index=True)
all_courses

,Course,Course Title,Department(s),Description,Credits,Repeat For Credit,Requisite,Requirement Designation,Typically Offered,Liberal Arts,Academic Career
0,ACC 231,Accounting Applications on Microcomputers,Accounting,This course provides accounting students with ...,3,No,Prerequisite: ACC 122 Students must also meet ...,NaN,All Terms,No,Undergraduate
1,ACC 331,Accounting Information Systems,Accounting,The course provides accounting students with t...,3,No,Prerequisite: English proficiency index of 55+...,NaN,All Terms,No,Undergraduate
2,ACC 331H,Accounting Information Systems (Honors),Accounting,The course provides accounting students with t...,3,No,This is an honors section. Students must have ...,NaN,All Terms,No,Undergraduate
3,ACC 122,Accounting Principles I,Accounting,The course covers the fundamental principles o...,3,No,Prerequisite: ESL 54 or higher and Math Profic...,NaN,All Terms,No,Undergraduate
4,ACC 222,Accounting Principles II,Accounting,This continuation of Accounting I progresses f...,3,No,Prerequisite: ACC 122 Students must also meet ...,NaN,All Terms,No,Undergraduate
...,...,...,...,...,...,...,...,...,...,...,...
181,MAR 300,Sales Principles and Practices,Business Management,This course is an overview of the process and ...,3,No,Prerequisite: MAR 100 Students must also be En...,NaN,"Fall, Spring",No,Undergraduate
182,SBE 400,Small Business Management,Business Management,This course covers the scope and trends of sma...,3,No,Prerequisite: (BUS 104 and SBE 100) or (SBE 20...,NaN,"Fall, Spring",No,Undergraduate
183,BUS 476,Social Entrepreneurship in Emerging Economics,Business Management,This is a study abroad course in which student...,3,No,Prerequisite: MAT 209,NaN,All Terms,No,Undergraduate
184,TTA 201,Travel Operations,Business Management,This course is designed to qualify individuals...,3,No,Prerequisite: (ENG 95 or ESL 95 or ESL 96) and...,NaN,"Fall, Spring",No,Undergraduate
185,HTT 301,World Markets,Business Management,This course is designed to analyze the global ...,3,No,Prerequisite: HTT 200,NaN,All Terms,No,Undergraduate

## Exporting

In [6]:
all_courses.to_csv('BMCC_Courses.csv', index=False, encoding='utf-8')